### ISSUE TITLE
Force close on launching AboutActivity

### ISSUE THREAD

**Issue by sajorahasan** [eggheadgames/android-about-box#23]
`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                      Process: com.ingridtech.antivirus, PID: 782
                                                                      java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:326)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:244)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                          at java.lang.Thread.run(Thread.java:761)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
                                                                          at com.eggheadgames.aboutbox.activity.AboutActivity.buildSocialNetworksCard(AboutActivity.java:180)
                                                                          at com.eggheadgames.aboutbox.activity.AboutActivity.getMaterialAboutList(AboutActivity.java:41)
                                                                          at com.danielstone.materialaboutlibrary.MaterialAboutActivity$ListTask.doInBackground(MaterialAboutActivity.java:156)
                                                                          at com.danielstone.materialaboutlibrary.MaterialAboutActivity$ListTask.doInBackground(MaterialAboutActivity.java:146)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:306)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:244) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                          at java.lang.Thread.run(Thread.java:761) `

**Comment by AlexDibrivnyy** [comment]
@mikemee LIbrary crashed, because developer, who used this it did not provide a `config.webHomePage` field. He left it null.

I think we need to add a posibility to leave some of fields empty. If they are null or "", then we will hide this item.  What do you think?

**Comment by mikemee** [comment]
@AlexDibrivnyy I agree. We should do like we did with the guide field recently and just hide anything that is left `null` or "".

**Comment by mikemee** [comment]
Fixed in #25. Waiting for the next release (today/tomorrow).
